<?php

namespace Modules\Pengaturan\Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Modules\Pengaturan\Entities\Pegawai;

class PegawaiDataTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();
        $data = [
            [
                'nip' => '195602221988111001',
                'nama' => 'ASMUJI',
                'id_staff' => 4,
                'id_jurusan' => 4,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => null,
                'status_karyawan' => 5,
                'username' => 'tefa',
                'noid' => null
            ],
            [
                'nip' => '197601222021211001',
                'nama' => 'MOH. DIMYATI AYATULLAH',
                'id_staff' => 4,
                'id_jurusan' => 1,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.Kom.',
                'status_karyawan' => 7,
                'username' => 'dimdim',
                'noid' => 1
            ],
            [
                'nip' => 'keluar 2012',
                'nama' => 'DIAN RANU CAHYONO',
                'id_staff' => 0,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => null,
                'status_karyawan' => null,
                'username' => null,
                'noid' => null
            ],
            [
                'nip' => '198801182021211001',
                'nama' => 'JAENI',
                'id_staff' => 14,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => null,
                'status_karyawan' => 7,
                'username' => 'jaeni',
                'noid' => 3
            ],
            [
                'nip' => '198403052021212004',
                'nama' => 'DIANNI YUSUF',
                'id_staff' => 4,
                'id_jurusan' => 1,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.Kom., M.Kom.',
                'status_karyawan' => 7,
                'username' => 'dianni',
                'noid' => 4
            ],
            [
                'nip' => '198310202014042001',
                'nama' => 'EKA MISTIKO RINI',
                'id_staff' => 4,
                'id_jurusan' => 1,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.Kom, M.Kom.',
                'status_karyawan' => 5,
                'username' => 'eka',
                'noid' => 7
            ],
            [
                'nip' => '197806132014041001',
                'nama' => 'MUHAMMAD FUAD ALHARIS',
                'id_staff' => 4,
                'id_jurusan' => 1,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.T.',
                'status_karyawan' => 5,
                'username' => 'haris',
                'noid' => 8
            ],
            [
                'nip' => '2011.36.072',
                'nama' => 'ALFAN JAMIL',
                'id_staff' => 5,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => null,
                'status_karyawan' => null,
                'username' => null,
                'noid' => 9
            ],
            [
                'nip' => '198401142019032006',
                'nama' => 'ERNA SURYANI',
                'id_staff' => 4,
                'id_jurusan' => 3,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.Eng.',
                'status_karyawan' => 5,
                'username' => 'erna',
                'noid' => 10
            ],
            [
                'nip' => '197905302021212005',
                'nama' => 'QURROTA A\'YUN',
                'id_staff' => 7,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.Ak.',
                'status_karyawan' => 7,
                'username' => 'yuyun',
                'noid' => 11
            ],
            [
                'nip' => '2008.36.011',
                'nama' => 'BAROROH BARIED',
                'id_staff' => 4,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => null,
                'status_karyawan' => 2,
                'username' => null,
                'noid' => 12
            ],
            [
                'nip' => '198601082021212003',
                'nama' => 'NIRMALA AYU NINGTYAS',
                'id_staff' => 7,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.E.',
                'status_karyawan' => 7,
                'username' => 'nirmala',
                'noid' => 14
            ],
            [
                'nip' => '197108272021211002',
                'nama' => 'ENES ARIYANTO SANDI',
                'id_staff' => 4,
                'id_jurusan' => 3,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.M.',
                'status_karyawan' => 7,
                'username' => 'enes',
                'noid' => 16
            ],
            [
                'nip' => '198212262021211001',
                'nama' => 'DENY SIGIT PRIYONO',
                'id_staff' => 24,
                'id_jurusan' => 4,
                'id_prodi' => 11,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.E.',
                'status_karyawan' => 7,
                'username' => 'sigit',
                'noid' => 17
            ],
            [
                'nip' => '198501222021211001',
                'nama' => 'SISWO HANDOKO',
                'id_staff' => 7,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T.',
                'status_karyawan' => 7,
                'username' => 'siswo',
                'noid' => 18
            ],
            [
                'nip' => '198106072021212007',
                'nama' => 'YUNI ULFIYATI',
                'id_staff' => 4,
                'id_jurusan' => 3,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.T.',
                'status_karyawan' => 7,
                'username' => 'yuni',
                'noid' => 19
            ],
            [
                'nip' => '198304132021211003',
                'nama' => 'ABDUL ROHMAN',
                'id_staff' => 4,
                'id_jurusan' => 2,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'ST., MT',
                'status_karyawan' => 7,
                'username' => 'rahman',
                'noid' => 20
            ],
            [
                'nip' => '197305312021212004',
                'nama' => 'ENNY PURWATI',
                'id_staff' => 7,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.Sos.',
                'status_karyawan' => 7,
                'username' => 'enny',
                'noid' => 21
            ],
            [
                'nip' => '198208072021211005',
                'nama' => 'DIAN RIDLO PAMUJI',
                'id_staff' => 4,
                'id_jurusan' => 2,
                'id_prodi' => 5,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.T.',
                'status_karyawan' => 7,
                'username' => 'dian',
                'noid' => 22
            ],
            [
                'nip' => '198611022014041001',
                'nama' => 'PRIO WIDHIA FAJAR',
                'id_staff' => 19,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.E.',
                'status_karyawan' => 5,
                'username' => 'prio',
                'noid' => 23
            ],
            [
                'nip' => '197903112021211002',
                'nama' => 'MOHAMMAD ABDUL WAHID',
                'id_staff' => 4,
                'id_jurusan' => 2,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.T.',
                'status_karyawan' => 7,
                'username' => 'abdul',
                'noid' => 24
            ],
            [
                'nip' => '198712202021211001',
                'nama' => 'HAIRUL SALAM',
                'id_staff' => 7,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T.',
                'status_karyawan' => 7,
                'username' => 'hairul',
                'noid' => 25
            ],
            [
                'nip' => '196501152021212001',
                'nama' => 'NINIK SRI RAHAYU W',
                'id_staff' => 4,
                'id_jurusan' => 2,
                'id_prodi' => 11,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.H., M.H.',
                'status_karyawan' => 7,
                'username' => 'ninik',
                'noid' => 26
            ],
            [
                'nip' => '198205072021211007',
                'nama' => 'CHAIRUL ANAM',
                'id_staff' => 4,
                'id_jurusan' => 2,
                'id_prodi' => 5,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.T.',
                'status_karyawan' => 7,
                'username' => 'anam',
                'noid' => 27
            ],
            [
                'nip' => '197810282024211007',
                'nama' => 'KHAIRUL MUZAKA',
                'id_staff' => 4,
                'id_jurusan' => 2,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.Eng-Res.',
                'status_karyawan' => 2,
                'username' => 'zaka',
                'noid' => 28
            ],
            [
                'nip' => '198708272024211012',
                'nama' => 'AGUS PRIYO UTOMO',
                'id_staff' => 4,
                'id_jurusan' => 1,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.ST., M.Tr.Kom.',
                'status_karyawan' => 6,
                'username' => 'banksonk',
                'noid' => 30
            ],
            [
                'nip' => '198301032021212008',
                'nama' => 'ARIADNE IKA MAHARANI',
                'id_staff' => 7,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'A.Md., S.E.',
                'status_karyawan' => 7,
                'username' => 'miss_inne',
                'noid' => 31
            ],
            [
                'nip' => '199112102021211002',
                'nama' => 'FARNAS ADY PRAMONO',
                'id_staff' => 7,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.E.',
                'status_karyawan' => 7,
                'username' => 'acil',
                'noid' => 32
            ],
            [
                'nip' => 'keluar 2011',
                'nama' => 'AGUS NURYANTO',
                'id_staff' => 0,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => null,
                'status_karyawan' => null,
                'username' => null,
                'noid' => null
            ],
            [
                'nip' => '2011.36.071',
                'nama' => 'SOLEHUDIN',
                'id_staff' => 33,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => null,
                'status_karyawan' => 2,
                'username' => 'solehudin',
                'noid' => 34
            ],
            [
                'nip' => '198505172015041003',
                'nama' => 'ZULIS ERWANTO',
                'id_staff' => 4,
                'id_jurusan' => 3,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.T.',
                'status_karyawan' => 5,
                'username' => 'zulis',
                'noid' => '35'
            ],
            [
                'nip' => '198106232024211007',
                'nama' => 'DRIYANTO WAHYU WICAKSONO',
                'id_staff' => 4,
                'id_jurusan' => 3,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.E., M.ST.',
                'status_karyawan' => 2,
                'username' => 'dwahyu',
                'noid' => '36'
            ],
            [
                'nip' => '198403312019031007',
                'nama' => 'MIRZA GHULAM RIFQI',
                'id_staff' => 4,
                'id_jurusan' => 3,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'ST., MST.',
                'status_karyawan' => 5,
                'username' => 'mrifqi',
                'noid' => '37'
            ],
            [
                'nip' => 'keluar 2013',
                'nama' => 'BAGUS TEGUH SUNARTO',
                'id_staff' => 0,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => null,
                'status_karyawan' => null,
                'username' => null,
                'noid' => null
            ],
            [
                'nip' => '2008.36.029',
                'nama' => 'MUHLAS',
                'id_staff' => 5,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => null,
                'status_karyawan' => 2,
                'username' => 'muhias',
                'noid' => '39'
            ],
            [
                'nip' => '197509272021211002',
                'nama' => 'HERMAN YULIANDOKO',
                'id_staff' => 4,
                'id_jurusan' => 1,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.T.',
                'status_karyawan' => 7,
                'username' => 'herman',
                'noid' => '40'
            ],
            [
                'nip' => '2008.36.031',
                'nama' => 'AHMAD JAYADI',
                'id_staff' => 10,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => null,
                'status_karyawan' => 2,
                'username' => 'ahmadjayadi',
                'noid' => '41'
            ],
            [
                'nip' => '198404032019032012',
                'nama' => 'VIVIEN ARIEF WARDHANY',
                'id_staff' => 4,
                'id_jurusan' => 1,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.T.',
                'status_karyawan' => 5,
                'username' => 'vivien',
                'noid' => '42'
            ],
            [
                'nip' => '197704042021211004',
                'nama' => 'DEDY HIDAYAT KUSUMA',
                'id_staff' => 4,
                'id_jurusan' => 1,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.Cs.',
                'status_karyawan' => 7,
                'username' => 'dedy',
                'noid' => '44'
            ],
            [
                'nip' => '198711032021212001',
                'nama' => 'DIAN MUJIANI',
                'id_staff' => 24,
                'id_jurusan' => 1,
                'id_prodi' => 4,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.E.',
                'status_karyawan' => 7,
                'username' => 'dianmjn',
                'noid' => '45'
            ],
            [
                'nip' => '198707272019031010',
                'nama' => 'GALANG SANDY PRAYOGO',
                'id_staff' => 4,
                'id_jurusan' => 2,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.T.',
                'status_karyawan' => 5,
                'username' => 'galang',
                'noid' => '46'
            ],
            [
                'nip' => '197506252021211003',
                'nama' => 'SUBONO',
                'id_staff' => 4,
                'id_jurusan' => 1,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.T.',
                'status_karyawan' => 7,
                'username' => 'bono',
                'noid' => '47'
            ],
            [
                'nip' => '198907072021212001',
                'nama' => 'DEVI MAHDALENA',
                'id_staff' => 35,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.E.',
                'status_karyawan' => 7,
                'username' => 'devi',
                'noid' => '49'
            ],
            [
                'nip' => '198301192021211006',
                'nama' => 'MOH. NUR SHODIQ',
                'id_staff' => 4,
                'id_jurusan' => 1,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.T.',
                'status_karyawan' => 7,
                'username' => 'shodiq',
                'noid' => '50'
            ],
            [
                'nip' => '198311052015041001',
                'nama' => 'DEVIT SUWARDIYANTO',
                'id_staff' => 4,
                'id_jurusan' => 1,
                'id_prodi' => 4,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.Si., M.T.',
                'status_karyawan' => 5,
                'username' => 'devit',
                'noid' => '52'
            ],
            [
                'nip' => '198801152021211002',
                'nama' => 'PANCA RIZA SUNANDAR',
                'id_staff' => 24,
                'id_jurusan' => 2,
                'id_prodi' => 5,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.E.',
                'status_karyawan' => 7,
                'username' => 'panca',
                'noid' => '53'
            ],
            [
                'nip' => '198604202021211001',
                'nama' => 'GINANJAR EKA SASMITA',
                'id_staff' => 2,
                'id_jurusan' => 3,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'A.Md.',
                'status_karyawan' => 7,
                'username' => 'ginanjar',
                'noid' => '55'
            ],
            [
                'nip' => '198606152021212003',
                'nama' => 'ELY TRIANA SARI',
                'id_staff' => 4,
                'id_jurusan' => 2,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.Pd., M.Pd.',
                'status_karyawan' => 7,
                'username' => 'elly',
                'noid' => '56'
            ],
            [
                'nip' => '2010.36.051',
                'nama' => 'AULIA EL HAKIM',
                'id_staff' => 4,
                'id_jurusan' => 1,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => null,
                'status_karyawan' => null,
                'username' => null,
                'noid' => '57'
            ],
            [
                'nip' => '198403112019031005',
                'nama' => 'ENDI SAILUL HAQ',
                'id_staff' => 4,
                'id_jurusan' => 1,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T., M.Kom.',
                'status_karyawan' => 5,
                'username' => 'endi',
                'noid' => '58'
            ],
            [
                'nip' => '198605212015041002',
                'nama' => 'M. SHOFI\'UL AMIN',
                'id_staff' => 4,
                'id_jurusan' => 3,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => 'Ir.',
                'gelar_blk' => 'S.T., M.T.',
                'status_karyawan' => 5,
                'username' => 'shofi',
                'noid' => '60'
            ],
            [
                'nip' => '198704272014041001',
                'nama' => 'UBNU FAJAR KARIMMULLOH',
                'id_staff' => 3,
                'id_jurusan' => 3,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'A.Md.',
                'status_karyawan' => 5,
                'username' => 'fajar',
                'noid' => '61'
            ],
            [
                'nip' => '198406142014041001',
                'nama' => 'EKO SLAMET RIYADI',
                'id_staff' => 3,
                'id_jurusan' => 2,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'A.Md.',
                'status_karyawan' => 5,
                'username' => 'ekochouw',
                'noid' => '63'
            ],
            [
                'nip' => '198107102021211007',
                'nama' => 'TRI PRASETYO',
                'id_staff' => 7,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.Ab.',
                'status_karyawan' => 7,
                'username' => 'treepras',
                'noid' => '64'
            ],
            [
                'nip' => null,
                'nama' => 'KUSNO',
                'id_staff' => 0,
                'id_jurusan' => null,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => null,
                'status_karyawan' => 2,
                'username' => null,
                'noid' => '65'
            ],
            [
                'nip' => '198405122021211003',
                'nama' => 'MOCHAMAD AROFI',
                'id_staff' => 2,
                'id_jurusan' => 2,
                'id_prodi' => null,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.T.',
                'status_karyawan' => 7,
                'username' => 'roby',
                'noid' => '66'
            ],
            [
                'nip' => '198706232019032009',
                'nama' => 'IKA YUNIWATI',
                'id_staff' => 4,
                'id_jurusan' => 2,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.Pd., M.Si.',
                'status_karyawan' => 5,
                'username' => 'ika',
                'noid' => '67'
            ],
            [
                'nip' => '198110072021212006',
                'nama' => 'DWI WAHYUNI',
                'id_staff' => 7,
                'id_jurusan' => 5,
                'id_prodi' => 14,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.E.',
                'status_karyawan' => 7,
                'username' => 'dwiyuni',
                'noid' => '68'
            ],
            [
                'nip' => '199111012021212001',
                'nama' => 'NOVINARI BUDI EKAWATI',
                'id_staff' => 7,
                'id_jurusan' => 0,
                'id_prodi' => null,
                'jenis_kelamin' => 'P',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.E.',
                'status_karyawan' => 7,
                'username' => 'novi',
                'noid' => '69'
            ],
            [
                'nip' => '198103232014041001',
                'nama' => 'ARYA PRAMUDITA',
                'id_staff' => 7,
                'id_jurusan' => 1,
                'id_prodi' => 6,
                'jenis_kelamin' => 'L',
                'gelar_dpn' => null,
                'gelar_blk' => 'S.E.',
                'status_karyawan' => 5,
                'username' => 'pramudita',
                'noid' => '71'
            ]
        ];

        foreach ($data as &$pegawai) {
            $pegawai['created_at'] = Carbon::now();
            $pegawai['updated_at'] = Carbon::now();
        }

        DB::table('pegawais')->insert($data);
    }
}
